name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          echo "========== UNIT TESTS =========="
          mvn -B -Denforcer.skip=true test

      - name: Build Java application
        run: |
          echo "========== MAVEN BUILD =========="
          mvn clean -B -Denforcer.skip=true package