name: Java CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws
  ECR_REPOSITORY: q2s1m9s9/jenkinsecr
  IMAGE_TAG: ${{ github.run_number }}
  IMAGE_URI: public.ecr.aws/q2s1m9s9/jenkinsecr:${{ github.run_number }}

  K8S_NAMESPACE: java-app
  K8S_DEPLOYMENT: java-app
  K8S_CONTAINER: java-app

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          echo "========== UNIT TESTS =========="
          mvn -B -Denforcer.skip=true test

      - name: Build Java application
        run: |
          echo "========== MAVEN BUILD =========="
          mvn clean -B -Denforcer.skip=true package

      - name: Login to AWS Public ECR
        run: |
          echo "========== ECR LOGIN =========="
          aws ecr-public get-login-password \
            --region $AWS_REGION |
          docker login \
            --username AWS \
            --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          echo "========== DOCKER BUILD =========="
          docker build \
            -t $IMAGE_URI \
            .

      - name: Push Docker image
        run: |
          echo "========== DOCKER PUSH =========="
          docker push $IMAGE_URI

      - name: Verify Kubernetes access
        run: |
          echo "========== KUBERNETES ACCESS =========="
          kubectl get deployment \
            $K8S_DEPLOYMENT \
            -n $K8S_NAMESPACE

      - name: Deploy to Kubernetes
        run: |
          echo "========== KUBERNETES DEPLOYMENT =========="

          kubectl set image deployment/$K8S_DEPLOYMENT \
            $K8S_CONTAINER=$IMAGE_URI \
            -n $K8S_NAMESPACE

          kubectl rollout status \
            deployment/$K8S_DEPLOYMENT \
            -n $K8S_NAMESPACE

      - name: Verify deployment
        run: |
          echo "========== DEPLOYMENT VERIFICATION =========="

          kubectl get deployment \
            $K8S_DEPLOYMENT \
            -n $K8S_NAMESPACE

          echo
          kubectl get pods \
            -n $K8S_NAMESPACE \
            -o wide

          echo
          kubectl get service \
            -n $K8S_NAMESPACE